#!/usr/bin/env bash
# Write the Android Gradle version properties consumed by the Tauri 2 Android
# template.
#
# Tauri CLI 2.5.0's generated app/build.gradle.kts reads
#   versionCode = tauriProperties.getProperty("tauri.android.versionCode", "1")
#   versionName = tauriProperties.getProperty("tauri.android.versionName", "1.0")
# from gen/android/app/tauri.properties, but that CLI never writes the file.
# Without it the published APK falls back to versionCode 1 / versionName "1.0"
# and ignores bundle.android.versionCode from tauri.conf.json. Write the file
# from tauri.conf.json so the APK carries the intended release metadata.
set -euo pipefail

CONF="${1:-clients/desktop/src-tauri/tauri.conf.json}"
DEST="${2:-clients/desktop/src-tauri/gen/android/app/tauri.properties}"

python3 - "$CONF" "$DEST" <<'PY'
import json
import sys
from pathlib import Path

conf_path, dest_path = sys.argv[1], sys.argv[2]
conf = json.loads(Path(conf_path).read_text(encoding="utf-8"))

version = conf.get("version")
android = (conf.get("bundle") or {}).get("android") or {}
code = android.get("versionCode")

if not isinstance(version, str) or not version:
    raise SystemExit(f"{conf_path}: missing version")
if not isinstance(code, int) or isinstance(code, bool) or code < 1:
    raise SystemExit(f"{conf_path}: missing bundle.android.versionCode")

dest = Path(dest_path)
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text(
    "# Autogenerated by scripts/release/android-version-properties.sh\n"
    f"tauri.android.versionCode={code}\n"
    f"tauri.android.versionName={version}\n",
    encoding="utf-8",
)
print(f"wrote {dest} versionCode={code} versionName={version}")
PY
